### ISSUE TITLE
请删除 .joplin-blog.json 配置文件

### ISSUE THREAD

**Issue by rxliuli** [ytianxia6/blog#4]
,joplin-blog.json 配置文件中包含着关键的 token，它让第三方程序能够在你的 PC 上直接访问你在 joplin 中的数据，这存在一些风险。最好从 gitignore 中忽略它，然后重新生成避免被利用现有的 token

https://github.com/ytianxia6/blog/blob/main/.joplin-blog.json

另外，最好还删除 joplin-cache.json 缓存文件，它是自动生成的文件，一般而言没必要提交上来

**Comment by ytianxia6** [comment]
多谢！目前我只在测试机上搞成功了，没能成功部署到 synology :(
